var NAVTREEINDEX0 =
{
"annotated.html":[6,0],
"class_linked_list.html":[6,0,0],
"class_node.html":[6,0,1],
"class_stack.html":[6,0,2],
"classes.html":[6,1],
"index.html":[],
"md__r_e_a_d_m_e.html":[0],
"md__r_e_a_d_m_e.html#autotoc_md19":[0,0],
"md__task1.html":[1],
"md__task1.html#autotoc_md21":[1,0],
"md__task2.html":[2],
"md__task2.html#autotoc_md23":[2,0],
"md__task2.html#autotoc_md24":[2,1],
"md__task3.html":[3],
"md__task3.html#autotoc_md26":[3,0],
"md__task4.html":[4],
"md__task4.html#autotoc_md28":[4,0],
"md__task5.html":[5],
"md__task5.html#autotoc_md30":[5,0],
"pages.html":[]
};
